% -------------------------------------------------------------------
%  Generated by MATLAB on 20-Jan-2018 18:59:57
%  MATLAB version: 9.2.0.538062 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

InteractionsLinearRegressionforPressure = saveVarsMat.InteractionsLinearRegressionforPressure; % <1x1 struct> unsupported class at InteractionsLinearRegressionforPressure.predictFcn

clear saveVarsMat;
